<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRoixene\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRoixene/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRoixene.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRoixene\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRoixene\appProdProjectContainer([
    'container.build_hash' => 'Roixene',
    'container.build_id' => '8d81a405',
    'container.build_time' => 1565318243,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRoixene');
