<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGodjvgo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGodjvgo/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGodjvgo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGodjvgo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGodjvgo\appProdProjectContainer([
    'container.build_hash' => 'Godjvgo',
    'container.build_id' => 'f94e71e1',
    'container.build_time' => 1565971714,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGodjvgo');
