api:
    prefix:  /api   
    type: rest
    resource: "@ApiBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/api/doc"
    