<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS6yrjiz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS6yrjiz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerS6yrjiz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerS6yrjiz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerS6yrjiz\appProdProjectContainer([
    'container.build_hash' => 'S6yrjiz',
    'container.build_id' => '50582c66',
    'container.build_time' => 1564872200,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS6yrjiz');
