<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFrrpvj0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFrrpvj0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFrrpvj0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFrrpvj0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFrrpvj0\appDevDebugProjectContainer([
    'container.build_hash' => 'Frrpvj0',
    'container.build_id' => '19ac745b',
    'container.build_time' => 1565971827,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFrrpvj0');
