<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFfpyfge\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFfpyfge/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFfpyfge.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFfpyfge\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFfpyfge\appDevDebugProjectContainer([
    'container.build_hash' => 'Ffpyfge',
    'container.build_id' => 'd06863a5',
    'container.build_time' => 1565921500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFfpyfge');
